---

- name: Install haveged
  yum:
    name: haveged
    state: "{{ 'latest' if haveged_pkg_state_latest else 'present' }}"
  notify:
    - restart haveged

- name: start haveged on boot
  service:
    name: haveged
    enabled: yes

- name: Check if init.d script exists
  stat:
    path: "{{ haveged_config_initd_path }}"
  register: haveged_initd_script

- name: Update init.d on RHEL 6 flavours
  lineinfile: >
    regexp='(\s*)\$\{HAVEGED_BIN\} -w (\d+)(.*)'
    line="\1${HAVEGED_BIN} -w {{ haveged_low_entropy_watermark }}\3"
    backrefs=yes
    dest="{{ haveged_config_initd_path }}"
    state=present
  notify:
    - restart haveged
  when: haveged_initd_script.stat.exists

...
