---
- name: Install haveged
  apt:
    name: haveged
    state: "{{ 'latest' if haveged_pkg_state_latest else 'present' }}"
  notify:
    - restart haveged

- name: start haveged on boot
  service:
    name: haveged
    enabled: yes

- name: Put template into position
  template:
    src: "{{ haveged_template_src }}"
    dest: "{{ haveged_template_path }}"
    mode: "{{ haveged_template_mode }}"
    owner: "{{ haveged_template_owner }}"
    group: "{{ haveged_template_group }}"
  notify:
    - restart haveged

...
